# Test generated by RoostGPT for test test-assembler-py using AI Model gpt

from __future__ import print_function
import sys
import unittest

def resetInterpreter():
    """
    resets the interpreter mind.
    """
    global eax, ebx, ecx, edx, zeroFlag, stack
    global variables, jumps, lines, tokens, returnStack
    eax = 0
    ebx = 0
    ecx = 0
    edx = 0
    zeroFlag = False
    stack = []
    jumps = {}
    variables = {}
    lines = []
    tokens = []
    returnStack = []

class TestInterpreterReset(unittest.TestCase):

    def setUp(self):
        global eax, ebx, ecx, edx, zeroFlag, stack
        global variables, jumps, lines, tokens, returnStack
        eax = 1
        ebx = 2
        ecx = 3
        edx = 4
        zeroFlag = True
        stack = [1, 2, 3]
        jumps = {'label': 5}
        variables = {'var': 6}
        lines = ['line1', 'line2']
        tokens = ['token1', 'token2']
        returnStack = [7, 8]

    def TestResetInterpreter35449d2449(self):
        resetInterpreter()

        global eax, ebx, ecx, edx, zeroFlag, stack
        global variables, jumps, lines, tokens, returnStack

        self.assertEqual(eax, 0)
        self.assertEqual(ebx, 0)
        self.assertEqual(ecx, 0)
        self.assertEqual(edx, 0)
        self.assertFalse(zeroFlag)
        self.assertEqual(stack, [])
        self.assertEqual(jumps, {})
        self.assertEqual(variables, {})
        self.assertEqual(lines, [])
        self.assertEqual(tokens, [])
        self.assertEqual(returnStack, [])

    def TestResetInterpreterValues(self):
        global eax, ebx, ecx, edx, zeroFlag, stack
        global variables, jumps, lines, tokens, returnStack

        self.assertNotEqual(eax, 0)
        self.assertNotEqual(ebx, 0)
        self.assertNotEqual(ecx, 0)
        self.assertNotEqual(edx, 0)
        self.assertTrue(zeroFlag)
        self.assertNotEqual(stack, [])
        self.assertNotEqual(jumps, {})
        self.assertNotEqual(variables, {})
        self.assertNotEqual(lines, [])
        self.assertNotEqual(tokens, [])
        self.assertNotEqual(returnStack, [])

if __name__ == '__main__':
    unittest.main()