# Test generated by RoostGPT for test test-assembler-py using AI Model gpt

from __future__ import print_function
import sys
import unittest

class TokenTester:
    def __init__(self, token, t):
        self.token = token
        self.t = t

class TestTokenTester(unittest.TestCase):

    def test_init_valid(self):
        test_token = "test_token"
        test_t = 5
        token_tester = TokenTester(test_token, test_t)
        self.assertEqual(token_tester.token, test_token)
        self.assertEqual(token_tester.t, test_t)

    def test_init_invalid(self):
        test_token = None
        test_t = None
        with self.assertRaises(TypeError):
            token_tester = TokenTester(test_token, test_t)

if __name__ == "__main__":
    unittest.main()