# Test generated by RoostGPT for test test-assembler-py using AI Model gpt

import unittest

# class for represent a token
class Token:
    def __init__(self, value):
        self.value = value

class TestToken(unittest.TestCase):
    def test_init_valid(self):
        token = Token("example")
        self.assertEqual(token.value, "example", "Token value should be 'example'")

    def test_init_invalid(self):
        with self.assertRaises(TypeError):
            token = Token(None)

if __name__ == "__main__":
    unittest.main()