# Test generated by RoostGPT for test test-assembler-py using AI Model gpt

from __future__ import print_function
import sys
import os
import unittest
import tempfile

lines = []

def loadFile(fileName):
    """
    loadFile: This function loads the file and reads its lines.
    """
    global lines
    fo = open(fileName)
    for line in fo:
        lines.append(line)
    fo.close()

class TestLoadFile(unittest.TestCase):

    def test_loadFile_success(self):
        # Create a temporary file with some content
        temp_file = tempfile.NamedTemporaryFile(delete=False)
        temp_file.write(b'Test line 1\nTest line 2\n')
        temp_file.close()

        # Call the loadFile function and check if the lines are loaded correctly
        loadFile(temp_file.name)
        self.assertEqual(lines, ['Test line 1\n', 'Test line 2\n'])

        # Clean up the temporary file
        os.unlink(temp_file.name)

    def test_loadFile_fileNotFound(self):
        # Call the loadFile function with a non-existent file
        with self.assertRaises(FileNotFoundError):
            loadFile("non_existent_file.txt")

if __name__ == '__main__':
    unittest.main()