# Test generated by RoostGPT for test test-assembler-vertex using AI Model vertex

from __future__ import print_function
import sys

def TestScan1480a0df86():
    """
    Test for scan()
    """
    lines = ['#include <stdio.h>', 'int main() {', '    return 0;', '}']
    scan()

    t.Log("lines: ", lines)
    assert len(lines) == 3, "lines should have 3 elements"


def main():
    t = unittest.TestCase()
    t.run(TestScan1480a0df86)

if __name__ == "__main__":
    main()