# Test generated by RoostGPT for test test-assembler-vertex using AI Model vertex

from __future__ import print_function
import sys


def TestResetInterpreter35449d2449():
    """
    Test resetInterpreter function.
    """
    # Test case 1:
    # Expected: eax, ebx, ecx, edx, zeroFlag, stack, variables, jumps, lines, tokens, returnStack are all reset to 0
    resetInterpreter()
    t.assertEqual(eax, 0)
    t.assertEqual(ebx, 0)
    t.assertEqual(ecx, 0)
    t.assertEqual(edx, 0)
    t.assertEqual(zeroFlag, False)
    t.assertEqual(stack, [])
    t.assertEqual(variables, {})
    t.assertEqual(jumps, {})
    t.assertEqual(lines, [])
    t.assertEqual(tokens, [])
    t.assertEqual(returnStack, [])

    # Test case 2:
    # Expected: eax, ebx, ecx, edx, zeroFlag, stack, variables, jumps, lines, tokens, returnStack are all reset to 0
    resetInterpreter()
    t.assertEqual(eax, 0)
    t.assertEqual(ebx, 0)
    t.assertEqual(ecx, 0)
    t.assertEqual(edx, 0)
    t.assertEqual(zeroFlag, False)
    t.assertEqual(stack, [])
    t.assertEqual(variables, {})
    t.assertEqual(jumps, {})
    t.assertEqual(lines, [])
    t.assertEqual(tokens, [])
    t.assertEqual(returnStack, [])


if __name__ == "__main__":
    t = unittest.TestLoader().loadTestsFromTestCase(TestResetInterpreter35449d2449)
    unittest.TextTestRunner(verbosity=2).run(t)